name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Set job variables
      run: |
        echo "IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/firefly-iii-webhooks" >> $GITHUB_ENV
        echo "IMAGE_TAG=$(date +%s)" >> $GITHUB_ENV

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag $IMAGE_NAME:latest --tag $IMAGE_NAME:$IMAGE_TAG

    - name: Push Docker image to GitHub Container Registry
      run: |
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$IMAGE_TAG
